### ISSUE TITLE
是否有考虑增添下拉框，列表框，文本框的自动换行

### ISSUE THREAD

**Issue by ChisaYuiyuki** [Xiaokang2022/maliang#10]
同标题，大佬有没有考虑过增添这些东西🤔

**Comment by Xiaokang2022** [comment]
有考虑过的，后续版本中会添加这些的，尽量在正式版发布前完成

**Comment by ChisaYuiyuki** [comment]
好，期待大佬的正式版

**Comment by Xiaokang2022** [comment]
@ChisaYuiyuki 

多行文本框暂时还没添加到 *tkintertools* 里面去，所以多行文本框的自动换行功能可能不会在正式版前实现了，因为我打算在正式版之后再写多行文本框，这个无疑是最最最复杂的控件。

*tkintertools 3.0.0* 正式版只是代表 API 稳定下来了，并不代表小部件会充分完善，所以没有多行文本框请谅解。

关于单行文本框，即输入框，既是单行的，就不会涉及到多行的问题，因此不会有自动换行的功能。

**Comment by Xiaokang2022** [comment]
@ChisaYuiyuki 

关于你说的下拉框和列表框，我不是很明白，这是指的同一个小部件吗？是 [ComboBox](https://learn.microsoft.com/zh-cn/windows/apps/design/controls/combo-box) 这样的？

我暂且认为它们是同一个小部件。

**Comment by Xiaokang2022** [comment]
我知道了，列表框类似于菜单栏那样，只不过是纵向全部显示出来的

**Comment by Xiaokang2022** [comment]
列表框（`ListBox`）目前不考虑添加，其一是目前还没有滚动条控件，其二是可以直接使用 `tkinter` 相关控件代替，此外，后续可能准备使用第三方的表格控件来实现效果更好的列表框，单独实现可能会产生不必要维护需求，且性能上无法保证。

在实现下拉框（`ComboBox`）后将关闭这个 Issue。

**Comment by Xiaokang2022** [comment]
已实现可编辑的下拉框控件（`ComboBox`）和不可编辑的下拉框控件（`OptionButton`），两者外观略有差别。

将在下个版本更新时关闭该 Issue。
