### ISSUE TITLE
可以增加支持 win7 系统吗?

### ISSUE THREAD

**Issue by stonereese** [Xiaokang2022/maliang#15]
### 🎯 Feature Description

win7 确实落伍了, 奈何写的一部分程序还需要给使用 win7 系统的用户使用, 请问后续可以支持 win7 吗?

### ⚠️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Xiaokang2022** [comment]
实际上，就 tkt 3 beta 版本而言，确实不支持 win7，因为其要求 Python 版本大于等于 3.10，而 win7 最多只支持 Python3.8。
不再得到开发支持的 tkt 2 为保留支持 win7 的功能，要求的 Python 版本被适当降低，只需 Python3.8 即可。如果你有需求，可以先使用 tkt 2。

tkt 3 未来并不一定会支持 Win7，这并不是技术上的问题，而是兼容性的问题。很多高级的 Python 语法都需要大于等于 Python3.10 才有（主要是类型提示语法），而且 Python3.8 在性能上与高版本相去甚远。

待 tkt 3 正式版发布后，我会在本仓库的讨论区发起一个投票，看看有多少占比的人觉得有必要支持 Win7，若超过半数，则我会尝试去实现一个本项目的特殊版本（通过其它方式安装）来支持 Win7。虽然是 tkt 本身支持 Win7 是不难的，只是为了保证兼容性而做的工作量比较大（后续不方便项目维护），但 tkt 3 部分功能所依赖的第三方包可能并不能支持 Win7，于是这将导致小部分功能在 Win7 没有。

**Comment by Xiaokang2022** [comment]
@stonereese 

非常抱歉，但我现在不得不放弃对 win7 的支持了，因为支持在 win7 系统上运行的 Python 最高版本是 Python3.8，但再过十几天 Python 官方就终止对 Python3.8 的支持了（今年十月份终止），也就是说，Python 官方将终止了对 win7 上 Python 的任何更新。

而且维护低 Python 版本的 `tkintertools` 的成本是非常巨大的，综合考量下我决定放弃 `tkintertools` 对 win7 的支持，非常抱歉。

当然，如果你愿意或者有其他人愿意，都可以 fork 该存储库并尝试兼容 Python3.8，`tkintertools` 不兼容低 Python 版本的主要原因就是使用了大量的高级语法，而这些语法对类型提示极为重要，在低版本中想要实现同样的效果需要付出大量是时间和精力去维护，对于每次 `tkintertools` 的更新都是如此。
