### ISSUE TITLE
更新完win32material后的一些问题

### ISSUE THREAD

**Issue by littlewhitecloud** [Xiaokang2022/maliang#20]
刚刚用纯python改完win32material，又一些函数名改了，不过我看完源码后要改的只有
https://github.com/Xiaokang2022/tkintertools/blob/4e59ad1aecc20b02201d4bd2b68872ef92aca06b/tkintertools/style/manager.py#L185
这个改成
```python
            win32material.SetWindowBorder(tools.get_hwnd(window), boarder_type)
```
其他没什么，就是README和requirements里面版本改成1.0.6就行了

**Comment by Xiaokang2022** [comment]
OK
