### ISSUE TITLE
为控件增加抗锯齿

### ISSUE THREAD

**Issue by AstralFlare-owo** [Xiaokang2022/maliang#21]
### Feature Description

对各种控件增加抗锯齿功能

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Xiaokang2022** [comment]
非常抱歉，此功能暂时无法实现，由于 `tkinter` 底层**貌似**不支持抗锯齿，故目前无法实现（~~也可能是由于我技术水平不足，以前尝试过，但没找到解决办法~~）

**Comment by Xiaokang2022** [comment]
@TuanZiGit 

对于该问题，有个不是非常好，但能用的解决方案，即控件不由 `Canvas` 类直接绘制，而是通过图片的方式进行“绘制”，控件处于各种状态时的反馈效果通过切换图片实现。

`Canvas` 支持带透明度的 png 格式图片，可以通过第三方库 `pillow` 来计算并生成对应大小的抗锯齿图片，然后通过 tkt 的 `Feature` 类来控制图片的切换，以实现抗锯齿。

虽然这种方式可以实现抗锯齿，但性能表现或许不太好，而且解决方式不够优雅，暂不对其实现。

**Comment by Xiaokang2022** [comment]
Python 已经在 3.14 Alpha 版本中做了对 Tk 9 的适配工作，正在对 Python 3.13 等其他版本做对应的适配。尽管 Tk 9 是自 Tk 8 发布 **27** 年以来的一个大更新，但其貌似仍然只在 macOS 上支持画布的抗锯齿功能。

受限于底层，Windows 上很难实现比较好的抗锯齿（要么不好实现，要么性能不佳，要么效果不行），因此我决定关闭该 Issue。如果未来 Tk 解决了这个问题，那么本项目将大概率会做好对应的适配工作。

当然，如果有人有比较的好的实现方法，我非常欢迎提 PR！
