### ISSUE TITLE
为tkt.Entry增加type参数

### ISSUE THREAD

**Issue by AstralFlare-owo** [Xiaokang2022/maliang#22]
### 🎯 Feature Description

为tkt.Entry增加type参数，允许类型"text","password"，以便应用掩码

### ⚠️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AstralFlare-owo** [comment]
或者增加一个update方法，可以绑定自定义的处理函数，实现此功能？

**Comment by Xiaokang2022** [comment]
@TuanZiGit 

此功能已实现，参数名为 `show`，详见：https://github.com/Xiaokang2022/tkintertools/commit/366b646301fec3c78c3f08e901be8601d7d18c90

此功能为 *3.0.0.beta3* 版本后添加的，将在 *3.0.0.beta4* 中可用

**Comment by Xiaokang2022** [comment]
参数名设为 `show` 是为了和原版 `tkinter` 保持一致

**Comment by Xiaokang2022** [comment]
在 https://github.com/Xiaokang2022/tkintertools/issues/17#issuecomment-2211350958 中提及了该功能
