### ISSUE TITLE
用pyinstaller 打包按钮会只剩边框

### ISSUE THREAD

**Issue by shu-shu-1** [Xiaokang2022/maliang#23]
### 🔖 Version

Latest development version

### 🔥 Platform

Windows 11

### ❓What Happened

tkt3.0 beta3中用pyinstaller 打包按钮会只剩边框
![image](https://github.com/user-attachments/assets/0f88c14a-f049-4d70-b006-0261d406b12d)
使用命令`pyinstaller demo0\main.py -F -w`

### ⚠️ Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Xiaokang2022** [comment]
这是由 `pyinstaller` 关于资源文件路径的寻找方式导致的。说简单点就是丢失了默认的样式文件。

*tkintertools 3.0.0.beta3* 中的样式文件路径是通过 Python 的特殊变量 `__file__` 确定的，这个值在非打包情况下是正确的，但打包之后，这个变量的值会变得不一样（`pyinstaller` 的问题），后续我会尝试想办法修改样式文件路径的确定方式，以尽量避免该问题。

或许你可以尝试用 [`nuitka`](https://github.com/Nuitka/Nuitka) 打包试试看？

**Comment by shu-shu-1** [comment]
> 这是由 `pyinstaller` 关于资源文件路径的寻找方式导致的。说简单点就是丢失了默认的样式文件。
> 
> _tkintertools 3.0.0.beta3_ 中的样式文件路径是通过 Python 的特殊变量 `__file__` 确定的，这个值在非打包情况下是正确的，但打包之后，这个变量的值会变得不一样（`pyinstaller` 的问题），后续我会尝试想办法修改样式文件路径的确定方式，以尽量避免该问题。
> 
> 或许你可以尝试用 [`nuitka`](https://github.com/Nuitka/Nuitka) 打包试试看？

nuitka如果使用 `--onefile` 会有同样现象

**Comment by shu-shu-1** [comment]
> 这是由 `pyinstaller` 关于资源文件路径的寻找方式导致的。说简单点就是丢失了默认的样式文件。
> 
> _tkintertools 3.0.0.beta3_ 中的样式文件路径是通过 Python 的特殊变量 `__file__` 确定的，这个值在非打包情况下是正确的，但打包之后，这个变量的值会变得不一样（`pyinstaller` 的问题），后续我会尝试想办法修改样式文件路径的确定方式，以尽量避免该问题。
> 
> 或许你可以尝试用 [`nuitka`](https://github.com/Nuitka/Nuitka) 打包试试看？

nuitka如果使用 `--standalone` 会有同样现象，但不含 `--standalone` 无法在其他电脑运行

**Comment by shu-shu-1** [comment]
> 这是由 `pyinstaller` 关于资源文件路径的寻找方式导致的。说简单点就是丢失了默认的样式文件。
> 
> _tkintertools 3.0.0.beta3_ 中的样式文件路径是通过 Python 的特殊变量 `__file__` 确定的，这个值在非打包情况下是正确的，但打包之后，这个变量的值会变得不一样（`pyinstaller` 的问题），后续我会尝试想办法修改样式文件路径的确定方式，以尽量避免该问题。
> 
> 或许你可以尝试用 [`nuitka`](https://github.com/Nuitka/Nuitka) 打包试试看？

经测试，pyinstaller打包后主程序获取os.path.dirname(__file__)返回值正常

**Comment by shu-shu-1** [comment]
> 这是由 `pyinstaller` 关于资源文件路径的寻找方式导致的。说简单点就是丢失了默认的样式文件。
> 
> _tkintertools 3.0.0.beta3_ 中的样式文件路径是通过 Python 的特殊变量 `__file__` 确定的，这个值在非打包情况下是正确的，但打包之后，这个变量的值会变得不一样（`pyinstaller` 的问题），后续我会尝试想办法修改样式文件路径的确定方式，以尽量避免该问题。
> 
> 或许你可以尝试用 [`nuitka`](https://github.com/Nuitka/Nuitka) 打包试试看？


不只是引用路径问题，我修改了`parser.py` 
``` python
if getattr(sys, 'frozen', False):
    # If the application is run as a bundle
    base_path = pathlib.Path(sys._MEIPASS)
else:
    base_path = pathlib.Path(__file__).resolve().parent.parent

BUILTIN_THEME_FOLDER: pathlib.Path = base_path / "theme"
```
pyinstaller打包时直接漏掉了主题文件夹，使用目录打包，手动补上主题文件即可，单文件打包添加`----add-data="【主题目录】;theme"`

**Comment by Xiaokang2022** [comment]
@shu-shu-1 

后续我会参考 [CustomTkinter](https://github.com/TomSchimansky/CustomTkinter) 的代码，看看他们是怎么解决这个问题的（他们应该也是有样式文件的）

**Comment by Xiaokang2022** [comment]
@shu-shu-1 

其实目前有个从代码层面的补救办法，就是将存放样式文件的文件夹单独拿出来，再在代码中以第三方主题的方式，通过相对路径的方式去调用，下面是一个示例（假设主题文件夹名为 *./example*）：

```python
import tkintertools.style as style

style.set_theme(folder="./example")
```

打包后把 example 文件夹放在和 exe 可执行文件同目录下即可。

适用当前测试版本：*3.0.0.beta4*

**Comment by Xiaokang2022** [comment]
@shu-shu-1 

为了简化问题的处理，我决定重新定义主题文件的格式，由原来的 *json* 格式改为 *py* 格式的，并将单个小部件的多个组件的主题融为一个变量，不再以小部件、组件来区分文件，而是直接以主题区分文件。

反正 *json* 格式的主题文件在使用时都要转换为 *py* 的数据，不如直接以 Python 基础类型（字典）格式存储。

同时，为解决打包后无法修改主题的问题（某些打包模式下 .py 格式的文件被加密，不方便修改），我将同时保留以 *json* 格式读取主题文件的方式，但格式仍与现在的不同（为了契合 *py* 格式），即以单个主题作为一个 *json* 文件。

下个 commit 就会实现这种方式。

**Comment by Xiaokang2022** [comment]
@shu-shu-1 

此 bug 已用一种较好的方式解决了，主题支持以 Python 文件和 JSON 文件两种方式导入，默认的主题以 Python 文件的方式导入（视作一般的 Python 包），这样就可以解决该 Issue 提到的 bug。如若用户想自定义主题，这两种方式都可以，混用也是可以的（但不推荐）。

Python 样式文件的格式与之前说的一致，但 JSON 的略有不同，不是以单个主题作为一个 JSON 文件，而是以单个主题作为一个文件夹，文件夹内是各个小部件的 JSON 文件，这样更改方便修改数据，直接作为单个文件会导致文件太大，不方便修改数据。

主题样式文件的格式见代码内的文档字符串，写的很详细了。

详见：https://github.com/Xiaokang2022/tkintertools/commit/4dcc4f5871d17594f185c5b0a6da05b46e99cac9
