### ISSUE TITLE
部件缩放的显示问题

### ISSUE THREAD

**Issue by wangquanqing** [Xiaokang2022/maliang#47]
### Version

Latest development version

### Platform

Windows 11

### What Happened

在创建子部件之前进行缩放，子部件的位置与预期位置不符：例如初始大小与全屏状态新创建部件的位置不同

```Python
import tkintertools as tkt


root = tkt.Tk()

canvas = tkt.Canvas(
    root, zoom_item=True, keep_ratio="max", free_anchor=True
)
canvas.place(
    width=1280,
    height=720,
    x=640,
    y=360,
    anchor="center",
)

def create_new_button():
    new_btn = tkt.Button(btn, (0, 0), text="456")
    new_btn.zoom()

btn = tkt.Button(canvas, (100, 100), text="123", command=create_new_button)

root.bind("<F11>", lambda event: root.fullscreen())
root.mainloop()
```

### Contact Details

1664906346@qq.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Xiaokang2022** [comment]
现在可以通过给 `zoom` 方法添加参数 `zoom_position=False` 来禁用异常的位置缩放了。

实现细节见：https://github.com/Xiaokang2022/tkintertools/commit/2be8e2482d587553b6e014f0939ee75fcf18a8fb

**Comment by Xiaokang2022** [comment]
该修复作为新版本发布，见：[`3.0.0rc4`](https://github.com/Xiaokang2022/tkintertools/releases/tag/3.0.0rc4)
