### ISSUE TITLE
Big Bug #1 TypeError: Tk.init() takes from 1 to 3 positional arguments but 4 were given

### ISSUE THREAD

**Issue by woodgreat** [Xiaokang2022/maliang#5]
Traceback (most recent call last):
  File "F:\tkintertools\test1.py", line 7, in <module>
    root = tkt.Tk(TITLE, WIDTH, HEIGHT)  # 创建窗口
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Tk.__init__() takes from 1 to 3 positional arguments but 4 were given

------------------------------------

import tkintertools as tkt  # 引入 tkintertools

# 第一部分
TITLE = '登录界面'  # 窗口标题
WIDTH = 1280  # 窗口宽度
HEIGHT = 720  # 窗口高度
root = tkt.Tk(TITLE, WIDTH, HEIGHT)  # 创建窗口

# 第二部分
X = 0  # 画布左上角横坐标
Y = 0  # 画布左上角纵坐标
BACKGROUND = '#BEE7E9'  # 画布背景颜色
canvas = tkt.Canvas(root, WIDTH, HEIGHT, X, Y, background=BACKGROUND)  # 创建画布

# 第三部分
canvas.create_text(640, 200, text='账 号 登 录', font=(tkt.FONT, 60))  # 文本显示
tkt.Entry(canvas, 450, 360, 380, 50, text=('账号', '点击输入账号'))  # 账号输入框
tkt.Entry(canvas, 450, 430, 380, 50, text=('密码', '点击输入密码'), show='●')  # 密码输入框
tkt.Button(canvas, 450, 500, 180, 50, text='注册')  # 注册按钮
tkt.Button(canvas, 650, 500, 180, 50, text='登录')  # 登录按钮

root.mainloop()  # 窗口进入消息事件循环

**Comment by Xiaokang2022** [comment]
<img width="959" alt="image" src="https://github.com/Xiaokang2022/tkintertools/assets/100004682/02e5ad2b-dacd-4a7f-96ac-6a717e02f48f">

教程只适用于稳定版，开发版本不支持。且 tkt 2 本就与 tkt 3 不完全兼容  
Tutorials are only available in the stable version and are not supported in the development version. TKT 2 is not fully compatible with TKT 3

**Comment by woodgreat** [comment]
那么，开发版对于新人怎么开始学习试用？谢谢

**Comment by Xiaokang2022** [comment]
> 那么，开发版对于新人怎么开始学习试用？谢谢

我目前还没有编写开发版本的教程和文档，其源代码中的文本字符串也只有部分，毕竟是 beta 版本，唯一能用的只有一个 demo，你可以在这里找到 demo 的代码：https://xiaokang2022.github.io/tkintertools/news/3.0.0/News/#demo-code

但 demo 也没有过多的解释性的注释，当前开发版本仅作演示和体验试用，并没有准备让其投入到生产环境中。

**Comment by woodgreat** [comment]
这个demo还是可以的，要是能系统性的测试和编写使用说明就好了。

**Comment by Xiaokang2022** [comment]
> 这个demo还是可以的，要是能系统性的测试和编写使用说明就好了。

这就不属于 beta 版本的事情了，而是正式版本的事情了

**Comment by woodgreat** [comment]
说的没错，我们在用上正式版前能做些什么？

**Comment by Xiaokang2022** [comment]
> 说的没错，我们在用上正式版前能做些什么？

等待以及支持本项目就行😁
