### ISSUE TITLE
确少ComboBox组件，这玩意还是有必要的把。。。。

### ISSUE THREAD

**Issue by JuZi233** [Xiaokang2022/maliang#52]
### Feature Description

确少ComboBox组件，这玩意还是有必要的把。。。。

### Possible Implementation

确少ComboBox组件，这玩意还是有必要的把。。。。

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Xiaokang2022** [comment]
Issue 重复，见：https://github.com/Xiaokang2022/tkintertools/issues/10

**Comment by Xiaokang2022** [comment]
那个下拉框是指 OptionButton（不可修改值）和 ComboBox（可修改值）这类的。

**Comment by JuZi233** [comment]
> 那个下拉框是指 OptionButton（不可修改值）和 ComboBox（可修改值）这类的。

也就是说下拉框等更新是吗，好的，谢谢
