### ISSUE TITLE
提示文本和输入文本同时显示

### ISSUE THREAD

**Issue by Rain-dewdrop** [Xiaokang2022/maliang#53]
### Version

Latest development version

### Platform

Windows 11

### What Happened

提示文本和输入文本同时显示

![2024-12-14 080652](https://github.com/user-attachments/assets/485de68d-fe34-480a-947b-98a341bd4c03)

```python
import tkintertools as tkt

size = 500, 300
root = tkt.Tk(size)
root.center()

cv = tkt.Canvas(root, zoom_item=True, keep_ratio="min", free_anchor=True)
cv.place(width=1280, height=720, x=640, y=360, anchor="center")   

InputBox = tkt.InputBox(cv, (20, 20), placeholder="InputBox")
InputBox.set("Test")

root.mainloop()
``` 

### Contact Details

3350941618@qq.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Xiaokang2022** [comment]
此为上个版本产生的 bug，现已修复，修复将在下个版本发布时更新，此 Issue 也将在下个版本发布时关闭。

非常感谢您发现了此 bug！
